### ISSUE TITLE
Unbeatable seed generated

### ISSUE THREAD

**Issue by JerryArr** [theonlydude/RandomMetroidSolver#105]
I tried playing the seed here: (https://randommetroidsolver.pythonanywhere.com/customizer/64a7f29e-91bf-478a-a5d2-34b3c9622ba4). Starting at Landing Site, I went down to the Morphing Ball spot and got Screw Attack. When I went back up to Pit Room, I used Screw Attack to break the blocks but there was no item there, as well as no enemies, and the door leading to Climb was gray, so I was softlocked.

**Comment by theonlydude** [comment]
Hello,
like in vanilla Super Metroid just taking the item at morph pedestal doesn't wake up Zebes.
you have to continue exploring blue Brinstar to wake up Zebes.

**Comment by JerryArr** [comment]
Alrighty, thank you!
