### ISSUE TITLE
Objective "Clear Lower Norfair" trigger error

### ISSUE THREAD

**Issue by josephrmoore** [theonlydude/RandomMetroidSolver#108]
Hi, I was playing the new objective mode with full area randomization on as well, and I randomly found the door to the back of Lower Norfair. The "Clear Lower Norfair" objective triggered as soon as I walked through the door. I could have just walked in and out and it would have counted as "clearing" Lower Norfair (but I stayed to look for stuff). In the vanilla game, this, of course, makes sense as the super gate prevents you from going in that way, but it's a little deflating to "earn" such a difficult objective so easily. I would imagine that wasn't your intention, so I thought I should let you know. Thanks!

**Comment by theonlydude** [comment]
Hello,
Indeed with 'Full Countdown' major split you can easily have no Major in an area.
Use another major split to be sure to have items to collect.

**Comment by josephrmoore** [comment]
Ok gotcha, yeah that's probably what happened. I assumed it was the entrance but it was probably the items were zero and I didn't notice that fact. Thanks, I will close this issue as I'm not sure it really is one.
