### ISSUE TITLE
Unsolvable area rando generated, checked against same preset

### ISSUE THREAD

**Issue by RevelationOrange** [theonlydude/RandomMetroidSolver#11]
Uploaded to the solver after creating the file the previous night, using the RevelStandard preset. Spoilers showed the items I had managed to collect, ending at the gauntlet, left and right. The last change I made to my preset was disabling main upper norfair hellruns and I think turning IBJ off, but that was almost a week ago. 
(Also, should be 'known techniques', but it being unfinishable is the main issue)

[bad_gen.VARIA_Randomizer_AFX99086_RevelStandard.sfc.zip](https://github.com/theonlydude/RandomMetroidSolver/files/2152180/bad_gen.VARIA_Randomizer_AFX99086_RevelStandard.sfc.zip)

**Comment by theonlydude** [comment]
Hello,
Indeed on the website the seed is not finishable, but when calling the solver in cli mode it does solve.
We'll investigate why.
In the meantime here's the spoiler generated in cli mode:
                                     Location Name         Area                           Sub Area Distance             Item     Difficulty Knows used Items used
------------------------------------------------------------------------------------------------------------------------------------------------------
                                     Morphing Ball:     Brinstar                      Blue Brinstar        1        PowerBomb            0.0 [] []
                     Energy Tank, Brinstar Ceiling:     Brinstar                      Blue Brinstar        1     SpeedBooster            5.0 ['CeilingDBoost'] []
                           Energy Tank, Terminator:     Crateria                Crateria Terminator        1            Morph            5.0 ['SimpleShortCharge'] ['SpeedBooster']
                        Power Bomb (blue Brinstar):     Brinstar                      Blue Brinstar        1            Super            0.0 [] ['Morph', 'PowerBomb', 'SpeedBooster']
                    Missile (blue Brinstar middle):     Brinstar                      Blue Brinstar        1          Missile            0.0 [] ['Super', 'Morph']
                    Missile (blue Brinstar bottom):     Brinstar                      Blue Brinstar        1            Super            0.0 [] ['Morph']
                       Missile (blue Brinstar top):     Brinstar                      Blue Brinstar        1            ETank            0.0 [] ['PowerBomb', 'Morph']
            Missile (blue Brinstar behind missile):     Brinstar                      Blue Brinstar        1        PowerBomb            0.0 [] ['PowerBomb', 'Morph']
                                              Bomb:     Crateria                     Crateria Bombs        1            Super            0.0 [] ['Morph', 'PowerBomb', 'Missile']
                     Power Bomb (Crateria surface):     Crateria              Crateria Landing Site        1            Super            0.0 [] ['Morph', 'PowerBomb', 'SpeedBooster']
                           Missile (Crateria moat):     Crateria              Crateria Landing Site        1            Super            0.0 [] ['Super', 'PowerBomb', 'Morph']
                         Missile (Crateria bottom):     Crateria              Crateria Landing Site        1        XRayScope            0.0 [] ['PowerBomb', 'Morph']
                         Missile (Crateria middle):     Crateria              Crateria Landing Site        1           Plasma            0.0 [] ['PowerBomb', 'Morph']
                          Super Missile (Crateria):     Crateria              Crateria Landing Site        1          Missile            5.0 ['SimpleShortCharge'] ['Morph', 'Reserve', 'ETank', 'PowerBomb', 'SpeedBooster']
                                            Spazer:     Brinstar                       Red Brinstar        2          Missile            0.0 [] ['Super', 'PowerBomb', 'Morph']
         Power Bomb (red Brinstar sidehopper room):     Brinstar                   Red Brinstar Top        1           Spazer           10.0 ['RedTowerClimb'] ['Super', 'PowerBomb', 'Morph']
              Power Bomb (red Brinstar spike room):     Brinstar                   Red Brinstar Top        1            Super            0.0 [] ['Super']
                 Missile (red Brinstar spike room):     Brinstar                   Red Brinstar Top        1            Super            0.0 [] ['Super', 'PowerBomb', 'Morph']
                            Reserve Tank, Brinstar:     Brinstar             Green Brinstar Reserve        2          Grapple            0.0 [] ['Missile', 'SpeedBooster', 'Morph']
                Super Missile (green Brinstar top):     Brinstar             Green Brinstar Reserve        1            Super            0.0 [] ['Missile', 'SpeedBooster']
           Missile (green Brinstar behind missile):     Brinstar             Green Brinstar Reserve        1            Super            0.0 [] ['Morph', 'Missile', 'PowerBomb', 'SpeedBooster']
      Missile (green Brinstar behind reserve tank):     Brinstar             Green Brinstar Reserve        1        SpaceJump            0.0 [] ['Missile', 'Morph', 'SpeedBooster']
                                       Charge Beam:     Brinstar                      Pink Brinstar        1            Varia            0.0 [] ['Morph', 'Missile', 'PowerBomb', 'SpeedBooster']
                     Super Missile (pink Brinstar):     Brinstar                      Pink Brinstar        1            Super            0.0 [] ['Morph', 'Super', 'PowerBomb', 'Missile']
                       Missile (pink Brinstar top):     Brinstar                      Pink Brinstar        1           HiJump            0.0 [] []
                    Missile (pink Brinstar bottom):     Brinstar                      Pink Brinstar        1            Super            0.0 [] []
                        Power Bomb (pink Brinstar):     Brinstar                      Pink Brinstar        1            Super            0.0 [] ['Super', 'PowerBomb', 'Morph']
                             Energy Tank, Waterway:     Brinstar                      Pink Brinstar        1            Super            5.0 ['SimpleShortCharge'] ['Morph', 'Missile', 'PowerBomb', 'SpeedBooster']
                             Energy Tank, Etecoons:     Brinstar                     Green Brinstar        1            ETank            0.0 [] ['Morph', 'PowerBomb', 'SpeedBooster']
                Power Bomb (green Brinstar bottom):     Brinstar                     Green Brinstar        1            Super            0.0 [] ['PowerBomb', 'Morph']
      Missile (green Brinstar below super missile):     Brinstar                     Green Brinstar        1          Missile            0.0 [] ['Morph', 'PowerBomb', 'Missile']
             Super Missile (green Brinstar bottom):     Brinstar                     Green Brinstar        1          Gravity            0.0 [] ['Super', 'PowerBomb', 'Morph']
                     Missile (green Brinstar pipe):     Brinstar                     Brinstar Hills        1            ETank            0.0 [] ['Morph', 'SpeedBooster', 'Super', 'Missile']
                                       X-Ray Scope:     Brinstar                       Red Brinstar        2            ETank            0.0 [] ['Grapple', 'PowerBomb', 'Morph']
                                        Space Jump:      Maridia                   Maridia Pink Top        2            Super            1.0 ['DraygonGrappleKill'] ['Morph', 'Gravity', 'SpeedBooster', 'Grapple', 'HiJump', 'Super', 'PowerBomb']
                              Energy Tank, Botwoon:      Maridia                   Maridia Pink Top        1        PowerBomb            1.0 [] ['Morph', 'Gravity', 'SpeedBooster', 'Grapple', 'Super', 'PowerBomb']
                                 Missile (Draygon):      Maridia                   Maridia Pink Top        1       SpringBall            1.0 [] ['Morph', 'Gravity', 'SpeedBooster', 'Grapple', 'Super', 'PowerBomb']
                          Energy Tank, Mama turtle:      Maridia                      Maridia Green        1          Missile            0.0 [] ['Missile', 'Gravity', 'SpeedBooster']
                Missile (green Maridia shinespark):      Maridia                      Maridia Green        1        PowerBomb            0.0 [] ['ETank', 'SpeedBooster', 'Super', 'Gravity', 'Reserve']
                     Super Missile (green Maridia):      Maridia                      Maridia Green        1            Super            0.0 [] ['Gravity', 'Morph']
                    Missile (green Maridia tatori):      Maridia                      Maridia Green        1            Super            0.0 [] ['Gravity', 'Missile']
                             Reserve Tank, Maridia:      Maridia                Maridia Pink Bottom        1            Super            0.0 [] ['Grapple', 'Super', 'Gravity', 'PowerBomb', 'Morph']
                    Super Missile (yellow Maridia):      Maridia                Maridia Pink Bottom        1            ETank            0.0 [] ['Grapple', 'Gravity', 'PowerBomb', 'Morph']
            Missile (yellow Maridia super missile):      Maridia                Maridia Pink Bottom        1            Super            0.0 [] ['Grapple', 'Gravity', 'PowerBomb', 'Morph']
               Missile (yellow Maridia false wall):      Maridia                Maridia Pink Bottom        1            Super            0.0 [] ['Grapple', 'Gravity']
              Missile (left Maridia sand pit room):      Maridia                Maridia Pink Bottom        1        PowerBomb            0.0 [] ['Grapple', 'Super', 'Gravity', 'PowerBomb', 'Morph']
             Missile (right Maridia sand pit room):      Maridia                Maridia Pink Bottom        1          Missile            0.0 [] ['Grapple', 'Super', 'Gravity', 'PowerBomb', 'Morph']
          Power Bomb (right Maridia sand pit room):      Maridia                Maridia Pink Bottom        1          Missile            0.0 [] ['Grapple', 'Super', 'Gravity', 'PowerBomb', 'Morph']
                            Missile (pink Maridia):      Maridia                Maridia Pink Bottom        1            ETank            0.0 [] ['Morph', 'Gravity', 'SpeedBooster', 'Grapple', 'Super', 'PowerBomb']
                      Super Missile (pink Maridia):      Maridia                Maridia Pink Bottom        1            Super            0.0 [] ['Morph', 'Gravity', 'SpeedBooster', 'Grapple', 'Super', 'PowerBomb']
                                       Spring Ball:      Maridia                   Maridia Sandpits        1           Charge            0.0 [] ['Grapple', 'HiJump', 'Super', 'Gravity']
                                       Plasma Beam:      Maridia          Maridia Forgotten Highway        1            Super            2.0 [] ['SpaceJump', 'Plasma']
                         Right Super, Wrecked Ship:  WreckedShip                   WreckedShip Main        2             Wave           1.56 [] ['SpaceJump', 'Morph', 'Gravity', 'Grapple', 'Super', 'PowerBomb']
                     Missile (Wrecked Ship middle):  WreckedShip                   WreckedShip Main        1            Super            0.0 [] ['Super', 'PowerBomb', 'Morph']
                 Super Missile (Wrecked Ship left):  WreckedShip                   WreckedShip Main        1            Super            0.0 [] ['Super']
                        Reserve Tank, Wrecked Ship:  WreckedShip                WreckedShip Gravity        1              Ice            0.0 [] ['Super', 'Morph', 'Varia', 'PowerBomb', 'SpeedBooster']
                                      Gravity Suit:  WreckedShip                WreckedShip Gravity        1            Super            0.0 [] ['Super', 'Varia', 'PowerBomb', 'Morph']
                            Missile (Gravity Suit):  WreckedShip                WreckedShip Gravity        1            Super            0.0 [] ['Super', 'Varia', 'PowerBomb', 'Morph']
                         Energy Tank, Wrecked Ship:  WreckedShip                   WreckedShip Back        1            ETank            0.0 [] ['Super', 'Gravity']
             Missile (outside Wrecked Ship bottom):     Crateria                 WreckedShip Bottom        1          Missile            0.0 [] ['PowerBomb', 'Morph']
                Missile (outside Wrecked Ship top):     Crateria                        WreckedShip        1            Super            0.0 [] ['Super']
             Missile (outside Wrecked Ship middle):     Crateria                    WreckedShip Top        1          Reserve            0.0 [] ['Super', 'Morph']
                        Missile (Wrecked Ship top):  WreckedShip                    WreckedShip Top        1            Super            0.0 [] ['Super']
                             Energy Tank, Gauntlet:     Crateria                  Crateria Gauntlet        2            Super            1.0 ['HardRoom-Gauntlet'] ['SpeedBooster', 'Reserve', 'ETank', 'PowerBomb', 'Morph']
                 Missile (Crateria gauntlet right):     Crateria                  Crateria Gauntlet        1            Super            1.0 ['HardRoom-Gauntlet'] ['SpeedBooster', 'Reserve', 'ETank', 'PowerBomb', 'Morph']
                  Missile (Crateria gauntlet left):     Crateria                  Crateria Gauntlet        1      ScrewAttack            1.0 ['HardRoom-Gauntlet'] ['SpeedBooster', 'Reserve', 'ETank', 'PowerBomb', 'Morph']
                                        Varia Suit:     Brinstar                          Warehouse        2            Super            1.0 [] ['Morph', 'Varia', 'SpeedBooster', 'Grapple', 'HiJump', 'Super', 'PowerBomb']
                                Energy Tank, Kraid:     Brinstar                          Warehouse        1            Super            0.0 [] ['HiJump', 'Super', 'PowerBomb', 'Morph']
                                   Missile (Kraid):     Brinstar                          Warehouse        1            ETank            0.0 [] ['HiJump', 'Super', 'PowerBomb', 'Morph']
                                     Hi-Jump Boots:      Norfair                   Norfair Entrance        1            Super            0.0 [] ['Missile', 'PowerBomb', 'Morph']
                           Missile (Hi-Jump Boots):      Norfair                   Norfair Entrance        1            Super            0.0 [] ['Missile', 'PowerBomb', 'Morph']
                       Energy Tank (Hi-Jump Boots):      Norfair                   Norfair Entrance        1            Super            0.0 [] ['Missile']
                               Missile (lava room):      Norfair                   Norfair Entrance        1          Reserve            1.0 [] ['Missile', 'Varia', 'Morph']
                          Missile (bubble Norfair):      Norfair              Bubble Norfair Bottom        1            ETank            0.0 [] ['Morph', 'PowerBomb', 'SpeedBooster']
                                          Ice Beam:      Norfair                        Norfair Ice        1          Missile            1.0 [] ['Super', 'Morph', 'Varia', 'PowerBomb', 'SpeedBooster']
                          Missile (below Ice Beam):      Norfair                        Norfair Ice        1            Super            1.0 [] ['Super', 'Varia', 'PowerBomb', 'Morph']
                            Energy Tank, Crocomire:      Norfair                          Crocomire        1          Reserve            1.0 [] ['Super', 'Grapple', 'Wave', 'Varia', 'SpeedBooster']
                                      Grapple Beam:      Norfair                          Crocomire        1            Super            1.0 [] ['SpeedBooster', 'PowerBomb', 'Morph']
                            Power Bomb (Crocomire):      Norfair                          Crocomire        1          Reserve            1.0 [] ['Grapple', 'ETank', 'Reserve']
                         Missile (below Crocomire):      Norfair                          Crocomire        1            Super            1.0 [] ['Morph']
                            Missile (Grapple Beam):      Norfair                          Crocomire        1            ETank            1.0 [] ['SpeedBooster']
                             Reserve Tank, Norfair:      Norfair             Bubble Norfair Reserve        1          Missile            1.0 [] ['Varia', 'Grapple', 'Super', 'PowerBomb', 'Morph']
                    Missile (Norfair Reserve Tank):      Norfair             Bubble Norfair Reserve        1            ETank            1.0 [] ['Varia', 'Grapple', 'Super', 'Morph']
               Missile (bubble Norfair green door):      Norfair             Bubble Norfair Reserve        1            Super            1.0 [] ['Varia', 'Grapple', 'Super']
                                     Speed Booster:      Norfair               Bubble Norfair Speed        1          Missile            1.0 [] ['Super', 'Varia']
                           Missile (Speed Booster):      Norfair               Bubble Norfair Speed        1        PowerBomb            1.0 [] ['Super', 'Varia']
                                         Wave Beam:      Norfair                Bubble Norfair Wave        1            Super            1.0 [] ['Varia', 'Missile']
                               Missile (Wave Beam):      Norfair                Bubble Norfair Wave        1            Super            1.0 [] ['Varia', 'Missile']
                         Missile (above Crocomire):      Norfair             Norfair Grapple Escape        1          Missile            1.0 [] ['SpaceJump', 'Morph', 'Varia', 'Wave', 'Super', 'PowerBomb']
                        Energy Tank, Brinstar Gate:     Brinstar                      Pink Brinstar        3            Super            1.0 [] ['Morph', 'Varia', 'PowerBomb', 'Ice', 'Wave']
                               Energy Tank, Ridley: LowerNorfair   Lower Norfair After Amphitheater        4            Super          15.38 [] ['SpaceJump', 'Morph', 'Varia', 'Gravity', 'SpeedBooster', 'ETank', 'Super', 'PowerBomb', 'Reserve']
      Missile (lower Norfair above fire flea room): LowerNorfair   Lower Norfair After Amphitheater        1            Super            1.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
   Power Bomb (lower Norfair above fire flea room): LowerNorfair   Lower Norfair After Amphitheater        1          Missile            1.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
                 Power Bomb (Power Bombs of shame): LowerNorfair   Lower Norfair After Amphitheater        1          Missile            1.0 [] ['SpaceJump', 'Morph', 'Varia', 'Gravity', 'Super', 'PowerBomb']
            Missile (lower Norfair near Wave Beam): LowerNorfair   Lower Norfair After Amphitheater        1            ETank            1.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
                            Energy Tank, Firefleas: LowerNorfair   Lower Norfair After Amphitheater        1            ETank            2.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
                       Missile (Mickey Mouse room): LowerNorfair  Lower Norfair Before Amphitheater        1          Missile            1.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
                                      Screw Attack: LowerNorfair         Lower Norfair Screw Attack        1            Super            2.0 [] ['SpaceJump', 'Varia', 'Gravity', 'PowerBomb', 'Morph']
                             Missile (Gold Torizo): LowerNorfair         Lower Norfair Screw Attack        1             Bomb            2.0 [] ['SpaceJump', 'Varia', 'Gravity']
                       Super Missile (Gold Torizo): LowerNorfair         Lower Norfair Screw Attack        1            ETank            2.0 [] ['SpaceJump', 'Varia', 'Gravity']
                                           The End:      The End                            The End        0          The End           1.04 [] []
Estimated difficulty: hard -----^---------- very hard
(15.37607820586544, True) : diff : /home/dude/download/bad_gen.VARIA_Randomizer_AFX99086_RevelStandard.sfc
5 : knows Used : /home/dude/download/bad_gen.VARIA_Randomizer_AFX99086_RevelStandard.sfc

**Comment by theonlydude** [comment]
[spoiler.txt](https://github.com/theonlydude/RandomMetroidSolver/files/2152213/spoiler.txt)
Hello,
Please see attached spoiler generated by the cli version of the solver.
We're investigating why the web version of the solver can't solve.

**Comment by theonlydude** [comment]
Hello,
Indeed there was a bug with detecting the layout patch, find attached the new spoiler.
[spoiler.txt](https://github.com/theonlydude/RandomMetroidSolver/files/2152559/spoiler.txt)

**Comment by RevelationOrange** [comment]
Oh god it wants me to do phantoon with only one etank lol
Cool, thank you for checking that out

**Comment by theonlydude** [comment]
Another bug is fixed regarding your issue.
The difficulty tables of the bosses were stored in the preset, and the difficulty tables have been updated.
The web was using the updated tables but the cli was using the tables in the preset.
As such now the tables are no longer stored in the preset.
