### ISSUE TITLE
(Feature request) Consider 1st super missile room access w/o Spore Spawn a skill toggle

### ISSUE THREAD

**Issue by nobuyukinyuu** [theonlydude/RandomMetroidSolver#115]
Currently, it seems assumed in logic that anyone can access the super missile room if they have super missiles already, but by default it seems the camera is set to despawn your shots to prevent access from the bottom and try to force you into visiting spore spawn.  With door randomizers set, a progression item can be gated in such a way that spore spawn is inaccessible to access this room.  

For my preset, I disabled all but the most basic techniques, and a seed was generated which required glitching thru to the super missile room early on for a required beam.  The run would've gone a lot smoother if I knew this technique was always in logic by default :)

**Comment by theonlydude** [comment]
hello,
we've already added a technique for it, it's available on beta: http://beta.varia.run/ : Backdoor to Spore Spawn item
it'll be in next release.

**Comment by nobuyukinyuu** [comment]
thanks!
