### ISSUE TITLE
Chrome identifies this as a malicious rom

### ISSUE THREAD

**Issue by purplepencilcase** [theonlydude/RandomMetroidSolver#117]
I'm not sure what was changed recently, but yesterday I could not download any randomizer roms from the website. Chrome keeps filing it as a malicious file and blocks it
<img width="827" alt="Screenshot 2023-07-06 at 22 32 33" src="https://github.com/theonlydude/RandomMetroidSolver/assets/66974134/91ba647a-5a6c-4570-912d-b976bc404774">

**Comment by theonlydude** [comment]
hello,
some users have reported that too.
for legal reason we can't have the super metroid rom uploaded on our server, so the website generates a patch which is applied on your local copy of the super metroid rom using javascript in your browser.
looks like chrome is thinking that generating a file for download in javascript is what virus do and blocks it, or maybe there's malicious sites on pythonanywhere so chrome flags all sites at pythonanywhere as dangerous.
Make sure that you're accessing the VARIA site in https, maybe it'll remove this message: https://randommetroidsolver.pythonanywhere.com/randomizer
I've looked at it on google and the only solution provided for Chrome is to disable Safe browsing, and it can only be done globally, not for just one website... So it's not a recommended solution.
I'm using Firefox and Chromium (Chrome open source alternative) and I don't have this annoying message.

**Comment by purplepencilcase** [comment]
Hello,

Thanks for the update. I might switch to Firefox for the time being as Chrome is not letting it download unless I disable the safe browsing completely.
