### ISSUE TITLE
Presets section global settings resets when switching tabs/sections

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#12]
Now that the presets are in a separate section it got a bit awkward to change around settings quickly.
When changing settings in the presets tab and you switch to solver, all of the settings return to their previous state, now you have to update the profile (and enter the password) each time you want to make any change.

**Comment by theonlydude** [comment]
Hello,
That's the intended behavior, you're not supposed to change you preset all the time (the techniques you know at a given time don't change).
Having the presets and the solver on the same page was confusing and intimidating for many users.

You can do what you want on your own computer using the command line interface of the solver and directly changing the json of the preset.

**Comment by elreymu** [comment]
I think i didn't explain myself well enough.

i wasn't trying to change known techniques, but stuff like "mininal, ,100%, any%" "gimme more health"  and such settings.
the issue is that before it was possible to change these kind of settings even on the premade presets (veteran, casual, etc) on the go and quickly see what changed) now it's impossible.
talking specifically about the global settings section.

**Comment by flohgh** [comment]
That was an issue indeed, it is fixed on the last update we released earlier today.

Those settings were moved to the solver page to be able to change them dynamically.
