### ISSUE TITLE
Varia Rando Mirrotroid bug

### ISSUE THREAD

**Issue by HELLKNlGHT** [theonlydude/RandomMetroidSolver#120]
Hi, I recently completed a Varia Rando Mirrotroid by completing "1 out 4 objectives?"
the timer came on screen when I completed just one objective out of four and I had to get to my ship?

I wish there was a way to attach the file here but I'll do my best with what is allowed.

Custom_VARIA_Mirrortroid_FX2831090292499200681_regular

*Custom* is only color palette, Samus sprite as Pyronette (vanilla colors, NOT RANDOMIZED COLORS) and the 
Ship sprite was the Capsule ship from Dragonball Z.

**Comment by flohgh** [comment]
Looking at your seed settings, you randomized a lot of them including "number of required objectives". The result of this randomization was 1. The intro screen upon loading your seed shows it.

![Intro](https://github.com/theonlydude/RandomMetroidSolver/assets/16208861/e49d8650-4dc3-44a3-a143-a84596373534)

If you're not interested in this feature, set the "number of required objectives" setting to "off". Then all objectives will be required, unless you have more than 9 objectives in your list, in which case the number of required objectives will be capped to 9.
