### ISSUE TITLE
Songs containing apostrophes in title fail to preview in Customizer

### ISSUE THREAD

**Issue by yuriks** [theonlydude/RandomMetroidSolver#121]
This seems to be caused by lack of escaping of single quotes in the link's embedded JS which causes it to fail to parse:
![image](https://github.com/theonlydude/RandomMetroidSolver/assets/341401/b025d0a2-f1b7-4594-90e1-672642d24e81)

**Comment by theonlydude** [comment]
thanks, I'll look into it.

**Comment by theonlydude** [comment]
it's fixed. thanks for the report.
