### ISSUE TITLE
Tracker incorrectly marks "Missile Outside Wrecked Ship Bottom" as a sequence break

### ISSUE THREAD

**Issue by Nimta** [theonlydude/RandomMetroidSolver#124]
In my current randomizer, I've ended up in a situation with morph, but without regular or power bombs. A key progression item - super missiles - is located at MOWSB, which I can reach with no problem, and leave too; collecting it only requires shooting the block with any weapon, jump + morph in, get the thing, and get out by shooting the same block again with ease. 
Despite this ease of entry, the tracker seems convinced that the item requires some kind of bombs to access - verified by checking off the "Missile Pink Brinstar Top" location, which is a power bomb, then checking off the missile on the other side of the no return ice beam door to its right to return my location "in bounds". Here is my rando rom, so that you can double check this.
[SM rando 2404.zip](https://github.com/theonlydude/RandomMetroidSolver/files/15106301/SM.rando.2404.zip)
I'm simply left to wonder why it thinks bombs are required. I don't think I've ever used bombs in the bottom half of that room.

**Comment by theonlydude** [comment]
hello,
indeed this location has a post availability check:
loc.PostAvailable = (
    lambda sm: sm.wor(sm.knowsSporeSpawnBackDoor(), # skill barrier for camera manip without creating a specific knows
                      sm.canPassBombPassages())
)

we added the bomb/power bomb requirement as you can get stuck in the respawing block if you're too slow.
to not create a new technique in the preset we reused the one for spore spawn back door access, when your preset knows it you don't need bomb/power bomb.

in the next release the location will no longer be displayed as sequence break, it'll have a ? on it:
![image](https://github.com/theonlydude/RandomMetroidSolver/assets/3090510/d49d9a35-0e17-4807-8c43-845df58fea8e)
