### ISSUE TITLE
QoL: Make map colors match door colors on colorblind mode

### ISSUE THREAD

**Issue by Martmists-GH** [theonlydude/RandomMetroidSolver#128]
Currently, the map door colors are always the same, even if the in-game doors are set to colorblind mode. 

Ideally, the colors of the map doors are modified to match the colorblind colors.

**Comment by flohgh** [comment]
Indeed that was an oversight, thanks for pointing it out. The fix should be available on the beta site shortly.

![image](https://github.com/user-attachments/assets/805d9462-7686-4aeb-86f2-61aa5e076f54)

**Comment by Martmists-GH** [comment]
Does this fix include door color randomization? (most notably Plasma Beam and Spazer doors, which are hard to distinguish on the map)

**Comment by flohgh** [comment]
Yes, they use the same palettes.
