### ISSUE TITLE
Bug: Gray Doors are no longer selectable in Plandomizer

### ISSUE THREAD

**Issue by LogiGameStar** [theonlydude/RandomMetroidSolver#131]
Gray doors used to be selectable in plando if you used a rando as the base that allows gray doors to be randomized, but ever since the update, they have no longer showed up on the selection when I make a plando. This used to only be an issue with beta, but now it's happening with the regular release too. And in case any setting I used could be conflicting in a way that prevents gray doors. I'll provide screenshots of one of the rando base settings I tried for my plando.

![Screenshot 2024-09-16 194845](https://github.com/user-attachments/assets/3d984d0d-6c5b-4025-9ece-ed6754aa08b0)
![Screenshot 2024-09-16 195059](https://github.com/user-attachments/assets/6fb6f349-10ef-4f4a-9178-4d0fcb7f4fc3)

**Comment by theonlydude** [comment]
hello,
bug fix has been deployed.
