### ISSUE TITLE
Spoiler showing which items got skipped and which couldn't be picked up

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#15]
When switching presets and selecting either "any" or "minimal" can you display which items (majors) got skipped and which ones couldn't get obtained when displaying the spoiler?

(I would like to also propose a couple of other minor suggestions for the solver, the credits stats and an  area randomizer softlock bug/glitch, should i post them in a separate thread?, don't want to feel like i am spamming, and thanks for making this great tool)

**Comment by flohgh** [comment]
Don't worry about spamming. Creating separate issues for each enhancement request or bug report is the only way to keep things organized! :)

**Comment by theonlydude** [comment]
Implemented.
Also implemented: when a seed can't be finished with the current preset, display the techniques to learn to reach the next locations.

Will be in the next release.

**Comment by theonlydude** [comment]
the release is out.
