### ISSUE TITLE
Incompatible transition causing grappling beam softlock in area randomizer

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#16]
I entered the door in red brinstar elevator room which is a vertical one, in this case it got me to the lava dive room (which is horizontal)
normally , it would work as intended, i played further and then came back to that door, but this time samus got stuck in the door (after entering in the lava dive room) while getting stuck in her grappling beam animation (i didn't even have grappling beam picked up), she stayed in a diagonal position, the grappling beam could be heard the entire time, i couldn't do anything and got stuck there.
tried it again later and couldn't replicate it, i don't have footage of it but as far as i remember i was holding R and shoot or did something that triggered it as i entered the door

**Comment by flohgh** [comment]
we had a similar issue (#9) triggered by unmorphing while going through a door.
This seems to be a general problem for "transition poses" that do not accept well to be forced in "elevator pose". Transition poses only last a few frames so you got unlucky. 
I'll investigate further: R is mapped to an angle on your controller?

**Comment by elreymu** [comment]
R had the vanilla setting, mapped to angle up.

i didn't have grapple at all, i could still switch weapons but couldn't do anything.

**Comment by flohgh** [comment]
Could not reproduce this particular bug, but found a more general fix for issue #9 (this one is easily reproductible) that should fix this one as well. Now forcing elevator pose is done in a much cleaner way than before.

Let us know if you experience anymore weird stuff when crossing incompatible door transitions.
