### ISSUE TITLE
Pickup strategy (any and minimal) question.

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#19]
On minimal the description says that it will pick up 5 super missile packs and 10 missile packs.
but on most seeds i have tested using the solver with the master preset (the randomized rom wasn't in master) or any other it picks more than 10 super missile packs (which would be 50 super missiles) , all items are enabled and minors quantity and energy is in vanilla and charge beam gets picked up.

I was guessing it's because charge usually gets picked up later in the game, but after charge gets picked up it still picks up more super missiles and missiles along the way (Even after defeating all the bosses, it picks up more super missiles even if it already has more than enough of them to beat mother brain).
Sometimes on Any it picks up more supers than minimal.
is this the intended behavior or how does it work?

**Comment by theonlydude** [comment]
Hello,
It looks like a regression. We'll fix it.

**Comment by theonlydude** [comment]
It's fixed, it'll in the next release.
