### ISSUE TITLE
Aqueduct Snail Clip Technique

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#20]
This technique is for getting  the missile and super missile in the maridia aqueduct without speedbooster.
would be good for the randomizer to consider this technique in the logic and add it in the presets aswell.
specially for the full randomization for when it puts a major progression item there.

here's a tutorial video by matrick
https://www.youtube.com/watch?v=fBQubU6h11U

**Comment by theonlydude** [comment]
Great, thank you, we'll add it !

**Comment by elreymu** [comment]
I forgot one important detail, the only requirement is GravitySuit (and Morphball obviously)
(Works without hi-jump boots aswell)

**Comment by theonlydude** [comment]
the release is out.
