### ISSUE TITLE
Issues w/ Crystal Flash

### ISSUE THREAD

**Issue by kddove85** [theonlydude/RandomMetroidSolver#23]
My button setup involves setting shoot to R, Angle Up to L and until your randomizer, angle down was unbound. However, with the availability of Angle Down being mapped to something unused, in this case A, I was able to utilize angle down and Crystal Flash (so I thought). I recently ran a randomizer where I had to do a hell run into Upper Norfair. Imagine my surprise when I attempted a crystal flash and nothing happened. I remapped the buttons to default, and crystal flash did work, so I eliminated the possibility of the issue being with my emulator.

As a request, if it's possible, can you rework the rom to not only use angle down if it is mapped to a face button, but also allow it to be used for a crystal flash. I have a controller setup that is similar to that of Behemoth's.

Please let me know if you have any comments, questions, or concerns, or if such a thing is possible.

**Comment by TeeGreg** [comment]
Not sure I understand correctly your problem, but inputs for crystal flash are {shoot, L, R, Down} not {Shoot, Angle Up, Angle Down, Down} thus if you crystal flash with an angle button mapped on the face button, you'll still have to press controllers L and R button to make it work.

**Comment by kddove85** [comment]
Okay. I'll explain... My button setting is as follows:

R = Shoot
Y = Run
B = Jump
X = Item Cancel
L = Angle Up
A = Angle Down
Select = Item Select

If you do attempt a Crystal Flash with Shoot, Down, L, R (or Shoot, Down, Angle Up, Shoot) it DOES NOT activate. If you attempt a Crystal Flash with Shoot, Down, Angle Up, Angle Down it also DOES NOT work.

You can not add either Angle down nor Angle up to a face button in the vanilla game, but your team managed a way to do so. I was wondering if it was possible - if you were able to map the angle up and downs to face button, if you could manipulate the crystal flash to activate in a similar fashion.

In response to your previous statement "inputs for crystal flash are {shoot, L, R, Down} not {Shoot, Angle Up, Angle Down, Down}" this is only true IF Angle Up and Angle Down are mapped in any order to L and R.

Thank you for your time. I look forward to hearing your response. And again, thank you for the randomizer and all the work your team does!

**Comment by flohgh** [comment]
The issue is not with angle up/down buttons here. I personally have angle up on L, angle down on Select, and dash on R. I can activate a crystal flash with down, L+R and shoot.

So I think the problem with your layout is that Shoot is on R.

We'll check if the CF routine can be patched, but since the code handling controls also has a patch to allow you to map angle up/down to any button, it will be hard to do anything without everything breaking apart. So don't get your hopes too high.

**Comment by kddove85** [comment]
I thank you for looking into it. I appreciate it. I won't get my hopes too high, I was just wondering if it was at all possible. If it is - GREAT! If not, nothing changes.

**Comment by TeeGreg** [comment]
On a vanilla game file, with 
Shoot = R
Run = B
Angle Up = L
Angle Down = off
A crystal can be performed pressing B L R & Down
If there is a problem, it is caused by the patch that allows to map angle up or down on a face button

**Comment by flohgh** [comment]
ok then :)
