### ISSUE TITLE
(Suggestion) A tweak to progression speed selection

### ISSUE THREAD

**Issue by PeteJohnston34** [theonlydude/RandomMetroidSolver#24]
Hello!
I have a suggestion for a tweak to the progression speed setting. I would love to be able to toggle off certain settings while still keeping the progression speed random. I have been doing a bunch of rando races lately, and we have found that both slowest and fastest aren't so great for racing. Fastest is a bit too boring, and slowest is too tedious. It would be great if we could roll seeds with randomized progression speeds, but without the possibility of "slowest" or "fastest".

Thanks!
Pete

**Comment by theonlydude** [comment]
Hello,
We'll try to see how we can let the user choose which progression speeds are available when set to random.

**Comment by theonlydude** [comment]
Hello,
It's added, it'll be in the next release. We've also added a new progression speed:
![image](https://user-images.githubusercontent.com/3090510/49501411-11e5cb00-f873-11e8-96d8-837969389e33.png)

**Comment by PeteJohnston34** [comment]
Amazing! Thank you for looking into that!
