### ISSUE TITLE
Pickups checkboxes suggestion

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#3]
Would it be possible to add checkboxes for each item?
Say i wanna skip hijump boots or grapple beam (or any item) and uncheck them from a list, then the solver would make a strategy around that or tell me if the run is not finishable, if it's not too much to ask
Maybe it's beyond the scope of the solver but thinking about it it has lots of potential as an experimentation tool, it's interesting to see what it comes up with.

(Already answered on another issue, posting here for organization sake)

**Comment by theonlydude** [comment]
Hello,
We've added your suggestion.

**Comment by flohgh** [comment]
Delivered. Please open a bug if there are problems with this feature.

**Comment by elreymu** [comment]
Wow that was really quick, thanks!
Going to test it right now
