### ISSUE TITLE
Zooming the website breaks the ability to read some popups

### ISSUE THREAD

**Issue by Nicholas-Steel** [theonlydude/RandomMetroidSolver#30]
Minor/Moderate issue with the Varia Randomizer website. Popups like this one can't be fully viewed when zooming the website (if you're hard of seeing and zoom websites to make it easier to read)...

![image](https://user-images.githubusercontent.com/11567846/66803839-2f3ff700-ef64-11e9-8025-53047af599df.png)

I can't scroll down the page to read the entire popup.

**Comment by theonlydude** [comment]
Hello,

Indeed, on the tracker page I've added a scroll on the help popup because it was too big.
I'll generalize it to all the help popups.

As a workaround to remove the help popup you can click on another smaller '?' button.

**Comment by Nicholas-Steel** [comment]
This has been resolved.
