### ISSUE TITLE
How to install on windows...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [theonlydude/RandomMetroidSolver#33]
What do i need to install the project on a windows web2py framework?
It is not possible to run the install.sh to create the symlinks, because the sh file is an linux/unix shell script and can not run on windows.

**Comment by theonlydude** [comment]
Hello,
You can run it using CYGWIN, you have to use python 3.6 or 3.7 from CYGWIN (it's a command line interface).
Beware that as Windows doesn't handle correctly mixcased file names, on the solver spoiler logs the items icons won't be the correct ones (it'll be the tracker's ones).

**Comment by theonlydude** [comment]
Have you been able to succeed in installing it on web2py on windows ?

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Sorry, no.
Me goal is to let the ramdomizer run as a local web server.
But at moment i have no success.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Maybe, You can assist me to bring the randomizer to work in windows?

**Comment by theonlydude** [comment]
I don't have a windows computer available, but I'll try to guide you (I've gathered the information on the internet, so it should work but I didn't test it)

first download mobaxterm there: https://mobaxterm.mobatek.net/download-home-edition.html, install it then launch it.
you click on the center of the screen on 'launch local terminal' or something like that.
then you type that : 
  apt-get install python3.6 git
  git clone git@github.com:theonlydude/RandomMetroidSolver.git
it'll download the prerequisites and create a copy of the varia sources.

then you can download this image of web2py that we created from our production environment: https://we.tl/t-bESSVF3MNf (link is valid for 7 days)
you need to put it in you mobaxterm home directory, to open a windows explorer there type this in mobaxterm:
  open /home/mobaxterm

then extract it:
  tar zxf ~/web2py.2.17.1.tar.gz

then clean the old symlinks:
  cd ~/web2py
  find . -type l -exec rm -f {} \;

recreate the new symlinks:
  ~/RandomMetroidSolver/web/install.sh

start web2py (it'll ask for a password, enter what you want, it's used to access the admin interface):
  cd ~/web2py
  python3.6 ./web2py.py

open firefox or chrome and go to this url: http://127.0.0.1:8000/
don't forget that because windows can't handle mix cased filenames correctly you won't have the correct images for items in the solver spoiler (it'll be the ones from the pause menu displayed on the tracker).

**Comment by theonlydude** [comment]
another link to download the web2py image: https://wetransfer.com/downloads/6a93b08ead56eae0a7cc55ddf78f5c5d20200217170101/6efa66f827bb9ac90206f6b9f7488e1120200217170115/eba2a0

**Comment by theonlydude** [comment]
solution offered.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hello,

Sorry for very late answer but i was busy in last few months.
Your solution was working and i was able to setup the randomizer in cygwin.
But when I try to update to current version i get an error.
I think the problen is the web2py package.
Is there any way to update the web2py package manualy?

**Comment by theonlydude** [comment]
what error do you have ?

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
When i load an randomized rom into solver then i get this error:
ROM roms/VARIA_Randomizer_FX2603582_regular_medium.json majors: Full area: False boss: False escape: False patches: ['Anti soft lock layout modifications', 'Custom new game', 'Gravity suit heat protection removed', 'VARIA tweaks'] activePatches: [10, 20, 21, 22, 23, 30, 31, 41, 1000, 1001, 1002]
Traceback (most recent call last):
  File "/home/Michael Groschupp/RandomMetroidSolver/solver.py", line 2170, in <module>
    standardSolver(args)
  File "/home/Michael Groschupp/RandomMetroidSolver/solver.py", line 2074, in standardSolver
    checkDuplicateMajor=args.checkDuplicateMajor, vcr=args.vcr, plot=args.plot)
  File "/home/Michael Groschupp/RandomMetroidSolver/solver.py", line 1421, in __init__
    self.loadRom(rom, magic=magic)
  File "/home/Michael Groschupp/RandomMetroidSolver/solver.py", line 327, in loadRom
    (self.areaTransitions, self.bossTransitions, self.escapeTransition) = self.romLoader.getTransitions()
  File "/home/Michael Groschupp/RandomMetroidSolver/rom.py", line 1536, in getTransitions
    return self.romReader.loadTransitions()
  File "/home/Michael Groschupp/RandomMetroidSolver/rom.py", line 329, in loadTransitions
    rooms = GraphUtils.getRooms()
  File "/home/Michael Groschupp/RandomMetroidSolver/graph_access.py", line 859, in getRooms
    if GraphUtils.isEscapeAnimals(vanillaExitName):
  File "/home/Michael Groschupp/RandomMetroidSolver/graph_access.py", line 842, in isEscapeAnimals
    return 'Flyway Right' in apName
TypeError: argument of type 'NoneType' is not iterable

But if i use the previous version (Your version provided for me) when it works.
So i think i need to know how i can prepare the web2py manualy.

Thank You.

**Comment by theonlydude** [comment]
when a new version is out we delete existing rom jsons, sessions in production.
you should do it too, in ~/web2py/roms/ and ~/web2py/applications/solver/sessions/

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
For some reasons the same problem.
I think i need a current version of web2py folder.

**Comment by theonlydude** [comment]
https://we.tl/t-EijIVpCnLZ

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Thx. :-)
For some reason this works now but how???

**Comment by theonlydude** [comment]
I don't know why it works now, but the good news is that it works.
I'm closing the issue.

**Comment by theonlydude** [comment]
FYI there's now docker images and scripts to locally run the website.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hi theonlydude :-)
could you share the current version of the web2py package for me again, please?
1000 thanks

**Comment by theonlydude** [comment]
hello,
you can check the web2py docker image build script that we now have in https://github.com/theonlydude/RandomMetroidSolver/blob/master/web/docker/web2py/Dockerfile
it contains all the steps to go from a vanilla web2py to a custom one for VARIA.

also note that we moved custom sprites in a separate github repository recently and the dockerfile has not been updated for it, you can check the readme for the new git commands:
dude@computer:~$ git clone --recurse-submodules git@github.com:theonlydude/RandomMetroidSolver.git
dude@computer:~$ cd RandomMetroidSolver
dude@computer:~/RandomMetroidSolver (master)$ git submodule foreach git checkout main

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hello,
thanks for your response.

I have a fully portable environment of cygwin so i don't use "Docker".
thanks.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hi,
in the meanwhile i tried Docker again with the updated script and it works.
But how i can copy out all required files to bring the randomizer to work in an cygwin environment?
Specially the web2py package?
Thank You. :-)

**Comment by theonlydude** [comment]
hello,
check in the DockerFile, there's the commands to get the web2py package:
RUN wget https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip && \
	unzip web2py_src.zip && \
	rm web2py_src.zip

if you follow the steps in the DockerFile you should be able to get it running in CYGWIN (not all the steps, only the get web2py source and VARIA customizations. here's the original one without our customizations: https://github.com/cabildocl/web2py-docker/blob/master/Dockerfile)
