### ISSUE TITLE
Add a section on README explaining how to run the randomizer locally/manually, on CLI, or something similar

### ISSUE THREAD

**Issue by kaiokmo** [theonlydude/RandomMetroidSolver#36]
As the website might sometimes go offline (for different reasons), it could be useful to be able to run the randomizer via CLI. That said, how about having a section on the README explaining how to do this?

**Comment by dagit** [comment]
This might also be nice for people that want to install the randomizer on a handheld device like a raspberry pi based thing so that they can generate randomized roms without an internet connection.

**Comment by theonlydude** [comment]
yep, I'll add that.

**Comment by theonlydude** [comment]
CLI documentation added to the readme.

You can join the VARIA discord if you have questions about using the CLI interface.
