### ISSUE TITLE
Suggestion: Allow removing items on tracker without using the undo button

### ISSUE THREAD

**Issue by enderbrah12** [theonlydude/RandomMetroidSolver#39]
To better explain, I've had many a time where I accidentally mark an item and don't realize it until later on. In the case of this tracker, I'd have to press undo to go all the way back to undo that item and then re add all the stuff that got undone in the process. To circumvent this, you could make it so just clicking an obtained item makes it go back to unobtained. Just a suggestion I had that'd help some people like me.

**Comment by theonlydude** [comment]
The seedless mode on http://beta.varia.run/ works like that, you interact with the inventory to add/remove items and clicking on a location always put the nothing item there.

I'll update the non seedless tracker to allow to uncollect a location by clicking again on it.

**Comment by theonlydude** [comment]
it's done, it's on beta: http://beta.varia.run/
