### ISSUE TITLE
Some of the preset options are gone for me

### ISSUE THREAD

**Issue by purplepencilcase** [theonlydude/RandomMetroidSolver#41]
Hi, I was using the randomizer with my preset and I accidentally deleted some of the randomizer parameters. For example, for progression speed I only have "fast" and "medium" options. I used to have others like VARIAble but they won't show up anymore. Is there a way to get back all of the options?
![varia](https://user-images.githubusercontent.com/66974134/84705613-94187a80-af53-11ea-8397-bee9e67bd470.png)

**Comment by theonlydude** [comment]
Hello,

This bug is known and fixed in beta version, it'll be in next release.

In the meantime you can reset your session by removing the VARIA cookie in Chrome:
![image](https://user-images.githubusercontent.com/3090510/84733398-686eb200-af9e-11ea-8801-acb458c2155a.png)

**Comment by purplepencilcase** [comment]
Ok thank you very much, I'll do that

**Comment by theonlydude** [comment]
pushed to production in last release.
