### ISSUE TITLE
Wiki Hyperlinks in location names (Suggestion)

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#5]
Since the main target audience for the solver are people who are beginners or not very familiar with all of the locations, or just people getting into the game, (I am familiar enough with most tricks in the game but there are still rooms that still i am not sure about their names), suggesting to add a wiki hyperlink to each location name in the spoiler section (Just like it's already done in the techniques section)

**Comment by theonlydude** [comment]
Hello,
The links to the rooms have been added to the spoiler.
