### ISSUE TITLE
Suggestion: Option to make pink doors exclusive to normal missiles

### ISSUE THREAD

**Issue by elreymu** [theonlydude/RandomMetroidSolver#65]
When you have super missiles that basically means you can open both pink and green doors making normal missiles not a concern if you get super missiles first.
Now that there's door color randomization maybe there would be even more unique or trolly seeds if there's an option that makes it so pink doors can only be opened by normal missiles.

**Comment by flohgh** [comment]
That's a really good idea, and not hard to do! we'll get to it :)

**Comment by theonlydude** [comment]
it has been implemented and it's available on beta.
