### ISSUE TITLE
Tracker logic does not function properly w/door randomizer

### ISSUE THREAD

**Issue by digitalthespian** [theonlydude/RandomMetroidSolver#66]
ROM: Custom_VARIA_Randomizer_DFX402591205628343781_DTRegMinus_VARIAble
I'm not sure exactly what happened, but early on the tracker stopped registering things properly.

**Comment by theonlydude** [comment]
hello,
do you have a screenshot of it ?
what do you mean by "early on the tracker stopped registering things properly" ?

**Comment by digitalthespian** [comment]
Hey! Sorry, it was really late and I was tired; I've attached a few screenshots of two other roms I've played since, both of which had similar issues; as far as I can tell, the logic doesn't properly understand how to tell if you've picked up a beam, either that or certain doors that are in the randomized pool are always treated as 'impassable'. However, both seeds were finishable according to the skills I had in my preset, so the randomizer part of the logic seems to work; or I just got lucky. This isn't all the issues, I just screenshotted early instances where it was marking things as available, and then it suddenly wasn't; one was the door to spazer, locked by a power bomb door, early supers/top of green brinstar was locked by yellow, and I had both morph and speed, and last was the moat and bomb torizo were both behind spazer, but didn't get marked as available after picking up spazer. I'm using snes9x-rr-1.60 (the multiworld compatible one) with the multiworld compatible rom.

Let me know if you need anything else!
Cheers,
DigitalThespian

________________________________

**Comment by digitalthespian** [comment]
![Spazer locked by yellow door but marked sequence break](https://user-images.githubusercontent.com/25490250/99459008-6f0da680-28fb-11eb-9a66-3b41191995ea.PNG)
![different seed--both moat and morph bombs locked by spazer and still marked sequence break after picking up spazer](https://user-images.githubusercontent.com/25490250/99459010-6fa63d00-28fb-11eb-9e0b-155e9f239528.PNG)
![early supers area marked as sequence break locked by yellow door--i have speed and morph](https://user-images.githubusercontent.com/25490250/99459014-703ed380-28fb-11eb-8a81-ac80044a6907.PNG)
It seems the screenshots didn't upload properly; here they are again.

**Comment by digitalthespian** [comment]
I have just discovered you can click the doors. I apologize; it seems to work fine when you actually use it properly. Whoops.

**Comment by theonlydude** [comment]
yes, you have to click on doors.
it would have been a big spoil to display the doors colors in the tracker.
