### ISSUE TITLE
Solver fails to find path out of Blue Brinstar/Crateria

### ISSUE THREAD

**Issue by yuriks** [theonlydude/RandomMetroidSolver#7]
With Total Normal X6299378

- First item location (Morph Ball) is an e-tank.
- At this point the solver seems to get stuck for some reason, this is as far as the solution log goes.
- Then get morph ball at Ceiling e-tank (with the d-boost)
- Get speed at Bomb Torizo
- Alcatraz and then doing a easy short charge+shinespark to destroy the bombable blocks
- Finish the rest of the seed

All techniques are enabled in the solver options.

**Comment by theonlydude** [comment]
Hello,

Thanks for the reporting of the issue.

In Total Normal we forgot to take into account the layout patch which change the red door at Construction Zone to a blue one, as such the solver couldn't enter Blue Brinstar Energy Tank Room.

We're fixing it.

**Comment by theonlydude** [comment]
Hello,
The fix has been has been pushed to the website.

**Comment by flohgh** [comment]
bug fixed and update released, closing

**Comment by yuriks** [comment]
Confirming it's fixed and now solving properly. Thanks!
