### ISSUE TITLE
Idea: Link sprite item names

### ISSUE THREAD

**Issue by VirtueAvatar** [theonlydude/RandomMetroidSolver#72]
E-Tank - Heart Container
Reserve Tank - Bottle / Piece of Heart / Red Potion

Charge Beam - Master Sword / Silver Arrows (check Super Missiles alternative)
Ice Beam - Ice Rod / Ice Arrows
Plasma Beam - Golden Bow / Ancient Arrows
Wave Beam - Slingshot / Fire Arrows
Spazer - Scattershot / Light Arrows

Missiles - Arrows
Super Missiles - Arrow Bundle / Silver Arrows (check Charge Beam alternative)
Power Bombs - Bombchus
Grapple Beam - Hookshot
X-Ray - Lens of Truth

Varia - Red Mail
Gravity - Blue Mail / Zora's Flippers

Hi Jump - Jump Magic
Speed Booster - Pegasus Boots
Space Jump - Fairy Magic / Hover Boots

Morph Ball - Child Link / Digging Mitts / Moon Pearl
Bomb - Bombs
Spring Ball - Roc's Feather
Screw Attack - Magic Cape / Thunder Magic

**Comment by theonlydude** [comment]
Varia -> Goron Tunic.
Gravity -> Zora Tunic.
Missiles -> Bomb Arrows
Supers -> Big Bomb Arrows
PBs -> Big Bomb
Charge -> Silver Arrows
Ice -> Ice Arrows
Wave Arrows?
Spazer -> Light Arrows 
Plasma -> Fire Arrows
Space Jump -> Roc's Feather

**Comment by theonlydude** [comment]
done:
    'link.ips': {
        'ETank': 'heart container',
        'Missile': 'bomb arrow',
        'Super': 'big bomb arrow',
        'PowerBomb': 'big bomb',
        'Grapple': 'hookshot',
        'XRayScope': 'lens of truth',
        'Varia': 'goron tunic',
        'SpringBall': 'roc feather',
        'Morph': 'moon pearl',
        'ScrewAttack': 'magic cape',
        'HiJump': 'jump magic',
        'SpaceJump': 'hover boots',
        'SpeedBooster': 'pegasus boots',
        'Charge': 'silver arrow',
        'Ice': 'ice arrow',
        'Wave': 'wave arrow',
        'Spazer': 'light arrow',
        'Plasma': 'fire arrow',
        'Bomb': 'bomb',
        'Reserve': 'bottle',
        'Gravity': 'zora tunic'
    }
