### ISSUE TITLE
Idea: Megaman sprite item names

### ISSUE THREAD

**Issue by VirtueAvatar** [theonlydude/RandomMetroidSolver#73]
'Varia Suit': 'Shadow Armor',
'Gravity Suit': 'Icarus Armor',

'Charge': 'Mega Buster',
'Ice': 'Ice Slasher',
'Wave': 'Wave Burner',
'Spazar': 'Chameleon Sting',
'Plasma': 'Laser Cutter',

'HiJump': 'Leg Upgrade',
'SpeedBooster': 'Dash Upgrade',
'SpaceJump': 'Rolling Cutter',

'Morph': 'Rolling Shield',
'Bomb': 'Bomb Bee',
'SpringBall': 'Bounce Ball',
'ScrewAttack': 'Screw Crusher',

'Missile': 'Photon Missile',
'Super': 'Sniper Missile',
'PowerBomb': 'Hyper Bomb',
'Grapple': 'Strike Chain',
'XRayScope': 'Shining Ray',

'Reserve': 'sub tank',
'ETank': 'heart tank',

**Comment by theonlydude** [comment]
done, thank you.
