### ISSUE TITLE
Idea: Win95 sprite item names

### ISSUE THREAD

**Issue by VirtueAvatar** [theonlydude/RandomMetroidSolver#74]
'Charge': 'Wireless Charge',
'Ice': 'App Freeze',
'Wave': 'Click-through',
'Spazer': 'Split Screen',
'Plasma': 'Antivirus',

'HiJump': 'Reboots',
'SpeedBooster': 'Overclocker',
'SpaceJump': 'Spacebar',

'Varia': 'Water Cooling',
'Gravity': 'Flood Filtering',

'Morph': 'Minimize',
'Bomb': 'Delete',
'SpringBall': 'Spring Wallpaper',
'Screw Attack': 'Denial of Service Attack',

'Missile': 'Click',
'Super': 'Double Click',
'PowerBomb': 'Delete All',
'Grapple': 'Drag and Drop',
'XRayScope': 'Aero Peek',

'Etank': 'SSD Drive',
'Reserve': 'HDD Drive'

**Comment by theonlydude** [comment]
done. thank you.
