### ISSUE TITLE
Idea: Mario/Mario NES/Luigi sprite item names

### ISSUE THREAD

**Issue by VirtueAvatar** [theonlydude/RandomMetroidSolver#76]
'Charge': 'Cheep Charge',
'Ice': 'Ice Flower',
'Wave': 'Superball',
'Spazer': 'Spiny Shelmet',
'Plasma': 'Hammer Suit',

'HiJump': 'Raccoon Suit',
'SpeedBooster': 'P-Speed',
'SpaceJump': 'P-Wing',

'Varia': 'Fire Flower',
'Gravity': 'Frog Suit',

'Morph': 'Mini Mushroom',
'Bomb': 'Bob-omb',
'SpringBall': 'Spring',
'Screw Attack': 'Super Star',

'Missile': 'Bullet Bill',
'Super': 'Banzai Bill',
'PowerBomb': 'POW Block',
'Grapple': 'Claw',
'XRayScope': 'Subspace',

'Etank': 'Magic Mushroom',
'Reserve': 'Reserve Mushroom'

**Comment by theonlydude** [comment]
added, thank you.
