### ISSUE TITLE
Idea for item names and sprites for Megaman X

### ISSUE THREAD

**Issue by Iron8127** [theonlydude/RandomMetroidSolver#77]
Charge Beam->X buster
Ice Beam->Shotgun Ice(icon)
Speed Booster-> Dash Boots
Plasma Beam->Ultimate Armor Buster
Spazer->Chameleon Sting(icon)
Energy Tank->Heart Tank
Reserve Tank->Sub Tank
Grapple Beam->Strike Chain(icon)
Varia Suit->Cyber Elf
Gravity Suit->Hyper Chip
Power Bomb->Giga Attack(icon)
Wave Beam->3rd Armor Buster
X-ray scope->2nd armor helmet
Super Missiles->homing torpedo(icon)
Normal Missiles->sniper missile (icon)
Space Jump->FalconArmr(chest)
Screw Attack->Electric Spark(icon)

Pallette change ideas.

Varia Suit-> Copy X's colors(if possible)
Gravity Suit->3rd Armor X's colors(with hyper chip)

**Comment by theonlydude** [comment]
Hello,

Thanks for the custom names but we already have custom names for this sprite:
    'megaman.ips': {
        'Varia': 'shadow armor',
        'Gravity': 'icarus armor',
        'Charge': 'mega buster',
        'Ice': 'ice slasher',
        'Wave': 'wave burner',
        'Spazer': 'chameleon sting',
        'Plasma': 'laser cutter',
        'HiJump': 'leg upgrade',
        'SpeedBooster': 'dash upgrade',
        'SpaceJump': 'rolling cutter',
        'Morph': 'rolling shield',
        'Bomb': 'bomb bee',
        'SpringBall': 'bounce ball',
        'ScrewAttack': 'screw crusher',
        'Missile': 'photon missile',
        'Super': 'sniper missile',
        'PowerBomb': 'hyper bomb',
        'Grapple': 'strike chain',
        'XRayScope': 'shining ray',
        'Reserve': 'sub tank',
        'ETank': 'heart tank'
    },

they are available on the beta website: http://beta.varia.run/
