### ISSUE TITLE
East Ocean with Ice Beam

### ISSUE THREAD

**Issue by Charles445** [theonlydude/RandomMetroidSolver#78]
Hope this is the right place...

You can traverse East Ocean pretty easily with Ice Beam from crabs.

https://www.youtube.com/watch?v=FIXfHqEHo-s

Allows for easy suitless wrecked ship access from crabs without High Jump Boots.
Relevant line of code (I think):
https://github.com/theonlydude/RandomMetroidSolver/blob/master/graph/vanilla/graph_helpers.py#L169

**Comment by theonlydude** [comment]
Hello,
Thanks for the trick, but we always require high jump when suitless.
you can still use it as a sequence break technique.
