### ISSUE TITLE
Control Freak integration

### ISSUE THREAD

**Issue by ShawnSigma** [theonlydude/RandomMetroidSolver#79]
Would it be possible to have Control Freak as an optional patch, alongside the rest of the QoL stuff like respin, infinite space jump etc.?
It would make some tricks impossible to perform, such as stuff that requires moonwalking, but once that's taken into account it'd be a pretty good optional addition for casual runs

**Comment by theonlydude** [comment]
hello,

unfortunately control freaks patch overlaps with existing patches.
it's too much work to relocate everything, so we won't add it.

ControlFreak.ips and AimAnyButton.ips overlap!
	PC:	['(0x175cb, 0x175ca)', '(0x88288, 0x88202)']
	SNES:	['($82f5cb, $82f5ca)', '($918288, $918202)']
ControlFreak.ips and minimizer_tourian.ips overlap!
	PC:	['(0x8fffe, 0x8ffee)']
	SNES:	['($91fffe, $91ffee)']
ControlFreak.ips and rando_speed.ips overlap!
	PC:	['(0x87668, 0x87660)']
	SNES:	['($90f668, $90f660)']
ControlFreak.ips and spinjumprestart.ips overlap!
	PC:	['(0x89f0b, 0x89ee2)']
	SNES:	['($919f0b, $919ee2)']
