### ISSUE TITLE
Add a override custom sprites option to the customizer (and two smaller ideas)

### ISSUE THREAD

**Issue by CheeseWaluigi** [theonlydude/RandomMetroidSolver#81]
The idea is to add a option on the Samus and ships proportion to override any custom sprites from a rom hack to replace with the selected custom sprites, obviously one of the drawbacks would be custom moves and suits but that's something that most ROM hacks don't have so it wouldn't be that big of a drawback in the end.

Either I just wanted to share this idea just in case it's possible, there's some rom hacks I would love to play with the given custom sprites like V I T A L I T Y with the JUSTIN BAILEY skin for an example.

Also another little idea is to add Samus' base sprite and vanilla ship as one of the options (presumably the first) so if you don't like the suit (or ship) redesign of a rom hack (& some of the custom ships from the skins) and want to bring it back to the vanilla look.

And with that, please make the ship a option on the color randomizer so the ship doesn't change color by default if the color randomizer is on.

**Comment by theonlydude** [comment]
hello,

you can look at SpriteSomething to apply custom sprites to hacks: https://github.com/Artheau/SpriteSomething
it's the tool we use to generate the custom sprites for our customizer.

supporting vanilla Super Metroid is already a lot of work, we can't support hacks on top of that.

custom ships are already excluded from color randomization, weird results happen when we randomize their palette.
