### ISSUE TITLE
Wii U VC Super Metroid rom seen as "Non vanilla ROM detected"

### ISSUE THREAD

**Issue by doodleintime** [theonlydude/RandomMetroidSolver#82]
So I have dumped the Super Metroid rom from my Wii U from the USA VC version twice, and both of the dumps result in the error "Non vanilla ROM detected" when you try to put it into the VARIA rando. What's interesting is that when you load that Wii U VC rom in an emulator (in this case, bsnes hd beta 10.6), the rom runs fine, though bsnes hd does not verify it as an official game.

I've been able to patch rom hacks onto that same rom, and they also work fine. I've even played some from start to finish. The fact that bsnes does not verify the unpatched rom as an offical game leads me to believe that there is a slight difference in the rom itself that barely affects anything.

Is it possible for a version of the rando without checksum validations could be sent to me to test if there are any issues with the rando that only appear when the rando patch is applied to this Wii U VC rom?

**Comment by theonlydude** [comment]
hello,

you can use the CLI version of the rando which doesn't check the rom checksum as explained in the github README.

**Comment by doodleintime** [comment]
I read the README just now (probably should have read it earlier) and I could not find anything that said that the CLI version of the rando had no checksum checks for the rom. However, you are the owner of this repository, so I will trust you when you say that the CLI version has no checksum checks for the rom.

But before I close this issue, I want to ask something. While there is a community preset folder in the repository, it has not been updated in 10 months according to said repository, and I made a community preset that I wanted to use for my rando playthrough yesterday, so what should I do about that? Do I have to set some parameters manually?

**Comment by miketrethewey** [comment]
Can you send it through [this tool](http://alttp.mymm1.com/game/checkcrc/) and post the resulting information?

**Comment by theonlydude** [comment]
community presets are stored in a separate github repository: https://github.com/theonlydude/community_presets

**Comment by theonlydude** [comment]
https://www.romhacking.net/forum/index.php?topic=25461.msg349234#msg349234

there's indeed changes in the wii U ROM.
there's changes in mother brain ASM, and we have patches on it too, so we'll stick to vanilla ROM.
