### ISSUE TITLE
Idea for a triforce hunt like randomizer 

### ISSUE THREAD

**Issue by Bokyubi** [theonlydude/RandomMetroidSolver#84]
Maybe include an option to collect an item (like a triforce piece) and when you collect x of them (the number you select) you have access to mother brain, I think this would make it interesting to have the option to skip bosses, and have players do certain routes to search for items more. You could even include the hud option to show how many 'triforce' pieces there are in an area.

**Comment by theonlydude** [comment]
hello,
it's complicated to add new items on super metroid as we already have many majors splits where we can't add new major items in them as we have a fixed list of major locations: Major/Minor, Chozo, Scavenger.
you can check beta: http://beta.varia.run/ there's a new parameter for the randomizer where you choose the objectives required to open access to mother brain. right now there's objectives about bosses and mini bosses but new ones should be added later, maybe some about items.

**Comment by Bokyubi** [comment]
Alright, thank you for getting back to me so soon!
