### ISSUE TITLE
new item logic

### ISSUE THREAD

**Issue by beauxq** [theonlydude/RandomMetroidSolver#85]
Do varia tweaks put in all the wrecked ship items before killing phantoon? or just the e-tank?

https://clips.twitch.tv/DeadAbstruseWasabiFloof-uXf0bprJZkOKSQE8

This could be a thing. Could CF clip to get back out.

**Comment by theonlydude** [comment]
hello,
this is too cryptic, we'll leave it as sequence break for master users.
in varia tweaks we'll add that all items in WS are available before killing phantoon and not only the etank.

**Comment by beauxq** [comment]
But players might like that left-side supers and right-side of attic are locked by Phantoon in world randomizer...
Maybe it shouldn't be that ALL items in WS are available.
