### ISSUE TITLE
Feature request: export skill preset to JSON

### ISSUE THREAD

**Issue by thieman** [theonlydude/RandomMetroidSolver#91]
I've been using the website to generate seeds but I'm looking into moving to using the CLI. It'd be really helpful if I could export skill presets as JSON since the web UI is really nice for modifying presets. This is also convenient for using community skill presets through the CLI.

I'm going to take a shot at a PR to do this.

**Comment by flohgh** [comment]
The community presets are stored in a git repository, you can find them here : https://github.com/theonlydude/community_presets

**Comment by thieman** [comment]
With the help of `theonlydude` on Discord, realized there's an existing endpoint for this that can be used to get the live data. Example:

`curl -d "preset=regular" https://randommetroidsolver.pythonanywhere.com/presetWebService`
